# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value
    mongo_host: 127.0.0.1
    mongo_port: 27017
    db: aston
    col_art: articles

#services:
#    mongo.service:
#        class: AppBundle\Service\MongoService
#        arguments: ['%mongo_host%', '%mongo_port%']
